### ISSUE TITLE
Hello, I wanna konw the purpose of create_image_of_text

### ISSUE THREAD

**Issue by SZhanZ** [kohjingyu/fromage#11]
Hello, I notice that there is a method called 'create_image_of_text' in utils.py. I can be aware of its function to draw a picture with the text caption, but cannot understand its role in the code where it is be called. Could you plz explain the purpose to set it? Thanks in advance~
<img width="760" alt="image" src="https://user-images.githubusercontent.com/43647263/226123907-4f9fa931-a246-4bf9-ad89-2ea7c94dad5a.png">

**Comment by kohjingyu** [comment]
Actually, this code is just for visualization purposes, it writes the image and the generated caption into Tensorboard outputs (https://github.com/kohjingyu/fromage/blob/main/fromage/evaluate.py#L180-L190). It is not used in the forward pass of the model.

Hope that makes sense!

**Comment by SZhanZ** [comment]
okay~ thanks alot
