### ISSUE TITLE
How to load dataset?

### ISSUE THREAD

**Issue by zhaoshitian** [kohjingyu/fromage#12]
It seems that I need to download the images using the url link in the CC3M dataset to run the dataload code. But I can't download some of those images because of the internet connection issue, so could you please share the dataset? Thank you!

**Comment by kohjingyu** [comment]
Unfortunately we are not allowed to redistribute the CC3M dataset. Please refer to their [webpage](https://ai.google.com/research/ConceptualCaptions/) to download it.

**Comment by zhaoshitian** [comment]
Okay, thank you
