### ISSUE TITLE
Asking for roadmap with more details?

### ISSUE THREAD

**Issue by ZeinabTaghavi** [kohjingyu/fromage#2]
I've been following the development of this project for a while and I'm excited about its progress. I was wondering if there's any information available about the future plans for feature enhancements.

Is there a roadmap or timeline available with more details? I would greatly appreciate a link or brief summary.

Thank you for your time and for developing such a great project!

**Comment by kohjingyu** [comment]
Thank you for your interest, and the kind comments! I'm hoping to have the training code up by this week, and then a web demo shortly after.
