### ISSUE TITLE
The cross entropy loss in training stage

### ISSUE THREAD

**Issue by Ziyang412** [kohjingyu/fromage#21]
Hi, thank you for the interesting work. 

From the teaser image(https://github.com/kohjingyu/fromage/blob/main/teaser.png), I noticed two cross entropy loss, one in image caption and one in retrieval. But according to the total loss in the original paper, I only saw the CE loss in the image caption stage. So, does the second CE loss applied in the training stage or am I missing anything?

Thank you in advance!

**Comment by kohjingyu** [comment]
Thanks for pointing this out! In this case, the second CE loss is indeed also applied during training. This is to allow the model to learn the proper [RET] embeddings. The retrieval CE loss is applied at lines 453-454 here:

https://github.com/kohjingyu/fromage/blob/92c6d6f6ea9cea38f0b0a12bcdb0cf3915d0e774/main.py#L453-L454

**Comment by Ziyang412** [comment]
Gotcha! Thanks!
