### ISSUE TITLE
I got Unexpected key(s) in state_dict error

### ISSUE THREAD

**Issue by eveningwalk** [kohjingyu/fromage#30]
Unexpected key(s) in state_dict: "model.logit_scale", "model.text_hidden_fcs.0.0.bias", "model.text_hidden_fcs.0.0.weight", "model.visual_embeddings.bias", "model.visual_embeddings.weight", "model.visual_fc.bias", "model.visual_fc.weight", "ret_input_embeddings.weight". 

I tried to fine tune your multi-modal model with my own dataset using your pre-trained data but I got the error above with activate --resume. After I installed requirements.txt and executed main.py then I installed many modules to figure out several no module errors.  With this errors above, to check the environment, I tried to install requirements.txt again and got several  version related errors. is that related with each other?

**Comment by kohjingyu** [comment]
I think this is the same issue as https://github.com/kohjingyu/fromage/issues/29#issuecomment-1740491866. Can you see if that helps?

**Comment by eveningwalk** [comment]
Yes, I figured out it. Thanks for your advise!
