### ISSUE TITLE
Can I use the embedding for training

### ISSUE THREAD

**Issue by LiJichen0114** [kohjingyu/fromage#35]
Hello, thank you for your work. I would like to ask if I can directly use cc3m_embeddings.pkl for model training? Or do I need to download the cc3m dataset? Looking forward to your reply.

**Comment by kohjingyu** [comment]
For training the model you would most likely have to use the CC3M dataset. The embeddings are mostly used as retrieval candidates during inference.

**Comment by LiJichen0114** [comment]
Thank you!
